# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "c323c5bd8585d875719db7570b91460e"
name = "moda-interact"
application_url = "https://moda-interact.onrender.com"
embedded = true
handle = "moda-interact"

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2026-07"

  [[webhooks.subscriptions]]
  uri = "/webhooks"
  topics = [
  "orders/create",
  "carts/create",
  "checkouts/create",
  "checkouts/update",
  "carts/update"
]

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_customers,read_orders,read_products"
optional_scopes = [ ]
use_legacy_install_flow = false

[auth]
redirect_urls = [ ]
